



FRONTEND_URL=http://localhost:5173
APP_BASE_URL=http://localhost:8080
DB_URL=jdbc:mysql://localhost:3306/resumebuilder
DB_USERNAME=root
DB_PASSWORD=root

BREVO_API_KEY=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


MAIL_USERNAME=af2848838@gmail.com
MAIL_PASSWORD=bjwh mmro sxaw crpj

JWT_SECRET=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970

CLOUDINARY_CLOUD_NAME=djk4jqda3
CLOUDINARY_API_KEY=325651863882878
CLOUDINARY_API_SECRET=vXWwkAoE4JykrH2ei4SVWvXybcU

RAZORPAY_KEY_ID=rzp_test_Syg2fE3Y40rX5A
RAZORPAY_KEY_SECRET=OTVsO501fBQd0DuUkc46iA8L