spring.application.name=resumeBuilderapi

# --- SQL Configuration ---
spring.datasource.url=jdbc:mysql://localhost:3306/resumebuilder
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true



## --- Brevo SMTP Configuration ---
#
## --- Brevo SMTP Configuration ---
#spring.mail.host=smtp-relay.brevo.com
#spring.mail.port=587
#
## LOGIN
#spring.mail.username=a25e55001@smtp-brevo.com
#
## \uD83D\uDE80 NAYI KEY GENEREATE KARKE YAHAN REPLACE KARO
#spring.mail.password=xsmtpsib-193608bf80149f14e6042ab164982c2b7a104fdd76eb71cb5bad0f8da84a7ac1-MygBkz5d8yZe3Ogk
#
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true
#
## SENDER (Must be verified in Brevo Dashboard)
#spring.mail.properties.mail.smtp.from=af2848838@gmail.com
#
## \uD83D\uDE80 YE DO LINES BHI ADD KARO FOR STRICT AUTHENTICATION
#spring.mail.properties.mail.smtp.starttls.required=true
#spring.mail.properties.mail.smtp.ssl.trust=smtp-relay.brevo.com

# ==========================================
# \uD83D\uDD25 NEW GMAIL SMTP CONFIGURATION (UPDATED)
# ==========================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587

# Aapka Gmail address
spring.mail.username=af2848838@gmail.com

# \u26A0\uFE0F WARNING: Yahan apna normal login password mat daalna.
# Google Account -> Security -> App Passwords se jo 16-digit ka code milega, use bina space ke yahan likho:


# spring.mail.password=dtep vqrr vffe hwey
spring.mail.password=this is mail pass

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

# Jo email id upar username me dali hai, wahi yahan aayegi
spring.mail.properties.mail.smtp.from=af2848838@gmail.com

#--- Appliction info ---
#ths is application url
app.base.url=http://localhost:8080

# --- Cloudinary information to upload image --- 
cloudinary.cloud_name=djk4jqda3

cloudinary.api_key=325651863882878

#cloudinary.api_secret=vXWwkAoE4JykrH2ei4SVWvXybcU

cloudinary.api_secret=this is secret key


#JWT Configuration 
jwt.secret=your-secret-key-here-change-this-in-production-with-more-secure-and-complicated-key 
#1hour
jwt.expiration=3600000   
 # 1 hour = 1000 * 60 * 60 (milliseconds)

#---   Razorpay Configuration  ---
razorpay.key.id=rzp_test_Syg2fE3Y40rX5A
#rzp_test_SHGtJWtXgKxkWZ

#razorpay.key.secret=OTVsO501fBQd0DuUkc46iA8L
razorpay.key.secret=this is rozarpay
#kth9SmF2W6fuXzFeZNJmXCWj
 
 
 
 
 
 
# this is all changes
# spring.mail.password=YOUR_GMAIL_APP_PASSWORD
#
#cloudinary.api_key=YOUR_CLOUDINARY_API_KEY
#cloudinary.api_secret=YOUR_CLOUDINARY_API_SECRET
#
#razorpay.key.id=YOUR_RAZORPAY_KEY_ID
#razorpay.key.secret=YOUR_RAZORPAY_KEY_SECRET


